### ISSUE TITLE
i am a student, can i work on your project for academic purposes?

### ISSUE THREAD

**Issue by beibarys98** [Grimmys/rpg_tactical_fantasy_game#18]
i am not the best at coding. but some stuff i guess i can do. have any suggestions for me to work on? i am cloning the game right now and going to play. can i add new features? or try to solve bugs?

**Comment by Grimmys** [comment]
Hi, 

Of course you can contribute !

I've listed some non-coding contributions in the README, but you can try adding new features / fixing bugs in your forked version of the game. When you think your contribution is ready, you can ask for a pull request : I will check it and merge it with the main project if it's good. :)

If you need any help  don't hesitate to contact me, it might be better to exchange through Discord or other chat platform so let me know by [e-mail](grimmys.programming@gmail.com).
