### ISSUE TITLE
want to change "fight summary" menu

### ISSUE THREAD

**Issue by beibarys98** [Grimmys/rpg_tactical_fantasy_game#26]
each time enemy attacks you get a menu and have to press "close" each time.
want to change this.
make it an optional feature for those who are interested in specific stats.
i want to add a button to the player menu.
after each enemy turn, you can go to player menu and press "diary" button, or "battle log" button.
where you can see each blow, each hp loss, etc.
i want its menu to look like a book.
similar to minecraft book and quill, or morrowind mission log.

**Comment by Grimmys** [comment]
Interesting idea.

I don't know if a diary or a battle log is the right thing to do ; never saw a turn-based game make something like it.
In Minecraft / Morrowind it's different, such a diary is used to store the details of the missions or the achievements.

But the problem you are pointing is real : I think there shouldn't be a button to press after each combat.

So... If you want to try something, go ahead! Don't hesitate to ask me for help if you don't understand something in the code.
