### ISSUE TITLE
some inconsistencies, in my amateur understanding of turn-based games

### ISSUE THREAD

**Issue by beibarys98** [Grimmys/rpg_tactical_fantasy_game#28]
1 - talking
-> did not move -> talk -> turn is finished [can't move, can't attack, can't open menu's but i think you should be able to] (trying to fix this)
-> move -> talk -> turn is finished [can't attack, can't open menu's but i think you should be able to] (trying to fix this)

2 - trading
-> trade -> move [can attack, can open menu's] (makes sense)
-> move -> trade [can attack , can open menu's] (makes sense)
-> move -> trade -> cancel -> return [don't stay where you moved but i think you should be able to] (trying to fix this)

3 - potion
-> move -> drink [can attack, can open menu's] (makes sense)
-> did not move -> drink [can't move but i think you should be able to] (trying to fix this)

- similar inconsistencies in attacking, visiting a house, visiting a shop, opening a chest, perhaps more (drinking from fountain?)

4 - suggestion
- this is my vision for this game, hope you agree:

- things you can do in a turn at most ONCE:
- - move
- - attack
- - wait (finishes the turn) (i would suggest "finish")

- all the other things can be done repeatedly and at any time, here is the combination table:
[insert action] move [insert action] attack [insert action] finish

**Comment by Grimmys** [comment]
I'm sorry to say that I not really agree... 
I'm afraid that this would be to " cheated ".
Like being able to make a trade to retrieve any consumables you need, use any consumables you want to boost yourself, move and attack after... All in one turn seems to be a lot for me. 

My initial idea was to have a turn plan like this :

1 - Move (if wanted) 
2 - Do non-terminal actions as many times as you want (such as trade or change your equipment) 
3 - Do a terminal action (such as visit or attack) 

It's a similar concept to the one in the Fire Emblem series I think. 

But I'm not an expert in " balancing ", maybe your vision is better.
So we can try it, but don't spend too much time if you don't succeed. :)

**Comment by beibarys98** [comment]
oh now i get it. terminating and non terminating actions. so, wait, attack, visit, talk terminates the turn. inventory, equipment, status, diary does not. but for some reason drinking potion terminates movement only, not the turn. what about it?

**Comment by Grimmys** [comment]
Because there is an order for the actions : movement should be the first action of the turn. Drink a potion is only a non terminating action, but should maybe change to a terminating one (use multiple potions in the same turn seems a lot).

I chose this order to prevent players from getting around the drawbacks, such as if they wanted to equip heavy armor to a character with low constitution, they could bypass the penalty movement by doing this : 

* Unequip
* Move without penalty
* Equip the heavy armor set to be prepare for the battle
* Attack

**Comment by beibarys98** [comment]
makes sense. i am going to try changing the order or the balance, as you said. if it gets hard, i will try other things. thanks.
