### ISSUE TITLE
what next?

### ISSUE THREAD

**Issue by beibarys98** [Grimmys/rpg_tactical_fantasy_game#30]
you have asked for sound effects and i did that bcz of it. game does not seem to have many bugs. may be one or two. but what is next? should we add more levels? story? maps? what can we add to make the game that you want?

**Comment by Grimmys** [comment]
Well, I have a lot of ideas of features to implement: new classes, new races, new items, new mechanics ofc and new levels ofc too.

I will add the mos't interesting and the easiest as issues (or maybe create a board? I think it's a feature available on github), to let you choose the ones you prefer. :)

Also, a little patch may be applied to the sound integration: the walking sound of a character is played even if the player chose to not move this character (if he only chose to attack for example). So maybe we can imagine that the " walking sound " is played only during the animation of a movement, to prevent this kind of situation, I don't know.

**Comment by Grimmys** [comment]
Okay, here is a project with some features that you can try to implement if you want : https://github.com/Grimmys/rpg_tactical_fantasy_game/projects/1

Tell me if you need extra informations.
