### ISSUE TITLE
Left click outside of a menu to leave it if possible

### ISSUE THREAD

**Issue by Grimmys** [Grimmys/rpg_tactical_fantasy_game#31]
Currently, the only way to exit a menu is to do a right click.
As pointed out by #24, it should be possible to do a left click outside of a menu to leave it if it's not a "blocking" menu.

Escape could also be a shortcut to leave a menu.

**Comment by SavainB** [comment]
can i work on this ?

**Comment by Grimmys** [comment]
Same answer as in the other issue, yes. 👍

**Comment by Grimmys** [comment]
Implemented by #66
