### ISSUE TITLE
Games crash when starting Chapter 1 - Level 1

### ISSUE THREAD

**Issue by ChristianumSolacium** [Grimmys/rpg_tactical_fantasy_game#57]
After closing the first dialogue pop-up of the level, the games crashes with this log:
[error message --LevelEntityCollections is not subscriptable--.txt](https://github.com/Grimmys/rpg_tactical_fantasy_game/files/9243289/error.message.--LevelEntityCollections.is.not.subscriptable--.txt)
The easiest way to fix it is to change entities.["foes"] to entities.foes

**Comment by Grimmys** [comment]
Closing the issue since it has been fixed
